### ISSUE TITLE
subitens no menu principal  do aegan-subtheme na versão mobile não funcionam - pois o item principal é clicável

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#104]

**Comment by thiagogomesverissimo** [comment]
@ricardfo conseguiu reproduzir?

Basta entrar em qualquer site pelo celular e tentar navegar nos subitens

**Comment by ricardfo** [comment]
Reproduzir eu consegui, mas não fui atrás de como resolver isso ainda.

**Comment by ricardfo** [comment]
Resolvido pelo estagiário Ricardo S.
