### ISSUE TITLE
Avaliar qual melhor módulo para popup de imagens: colobox ou ng-lightbox - LISA

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#108]

**Comment by thiagogomesverissimo** [comment]
Depois de definido qual é melhor, inserir no composer e dar as permissões necessárias

**Comment by ricardfo** [comment]
O Colorbox é melhor mas tenho uma dúvida, o site do Lisa já utiliza o **juicebox**, mesmo assim devemos instalar o **colorbox**?

**Comment by thiagogomesverissimo** [comment]
O juicebox é bem limitado e faz propaganda da versão paga. O colorbox ou lightbox são mais genéricos. Mas tem que baixar ambos e testar.
