### ISSUE TITLE
O módulo BeautyTips para o site Semiótica

### ISSUE THREAD

**Issue by ricardfo** [fflch/drupal#134]
O site em drupal 7 usava este módulo para criar os hints dos eventos da agenda, verificar a possibiliade de instalação do mesmo para drupal 8

**Comment by thiagogomesverissimo** [comment]
Existe versão para D8, funcionou?

**Comment by ricardfo** [comment]
Têm a versão alpha para drupal8 mas não funcionou. 
Ele utiliza duas funções ( **module_exists(), variable_get()** ) que foram deprecada do drupal.

**Comment by thiagogomesverissimo** [comment]
Então, só avisar o professor que não tem.
