### ISSUE TITLE
webform export xlsx funciona local, mas não fuciona em produção. No log não da erro. 

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#136]
idem: https://github.com/fflch/drupal/issues/143

**Comment by thiagogomesverissimo** [comment]
mesma task que: https://github.com/fflch/drupal/issues/136

**Comment by acesarfs** [comment]
Eu não entendi muito bem o que fazer nessa issue. Também não entendi a relação com as issues 141 e 143.

**Comment by thiagogomesverissimo** [comment]
Essa vou fechar, pois é um módulo que nao usaremos mais

**Comment by thiagogomesverissimo** [comment]
Nada. Essa issue tá fechada
