### ISSUE TITLE
não mostrar erros/warnings para usuários da role FFLCH - aplicar arquivo yml

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#139]
Pela interface a configuração fica em admin/config/development/logging. Deve-se identificar o arquivo yml correspondente

**Comment by acesarfs** [comment]
Pelo que entendi, essa configuração define o que vai ser exibido para o usuário e o padrão é exibir nenhuma mensagem de erro. Sendo assim, já não são mostrados erros/warnings para qualquer usuário. Estou certo?

**Comment by thiagogomesverissimo** [comment]
O botão de registros de log recentes não está aparecendo para a Role FFLCH, então acho que não.

**Comment by thiagogomesverissimo** [comment]
O padrão do Drupal é não mostrar. Mas algusn sites migrados do 6 e do 7 estão configurados para mostrar.
Vamos fazer o yml para deixar igual em todos.

**Comment by acesarfs** [comment]
Se entendi agora, devo colocar a linha:

error_level: hide

no arquivo user.role.fflch.yml. Essa linha deve ser colocada antes da relação de permissões. É isso?

**Comment by thiagogomesverissimo** [comment]
nõa.
`error_level: hide` deve ir no arquivo yml onde vc a encontrou

**Comment by acesarfs** [comment]
Como a issue mencionava "para usuários da role FFLCH " pensei que era nesse escopo. Se for assim, acho que já foi feito pelo Ricardo na issue 82. O arquivo web/profiles/contrib/fflchprofile/modules/fflch_configs/config/mandatory/system.logging.yml já está configurado.

**Comment by thiagogomesverissimo** [comment]
então pode fechar a issue =)
