### ISSUE TITLE
Remover o módulo select_or_other pois essa função já existem em cck_select_other

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#141]
@acesarfs pode fazer os mesmo passos de:
https://github.com/fflch/drupal/issues/143

**Comment by acesarfs** [comment]
O módulo select_or_other foi removido do arquivo composer.json.

**Comment by thiagogomesverissimo** [comment]
Lembre que além de remover do composer json tem que remover a quente dos que estão  em  Produção

**Comment by thiagogomesverissimo** [comment]
vc fez um drush @$site pm-uninstall select_or_other  em todos sites?
