### ISSUE TITLE
remover webform_submission_files_download. Essa fucionalidade tem no webform nativo

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#143]

**Comment by thiagogomesverissimo** [comment]
@acesarfs pode remover esse módulo. Lembrando que não basta remover do composer.json, é necessário:

- Remover do /web/profiles/contrib/fflchprofile/modules/fflch_configs/src/installed.txt
- Remover do composer.json
- "A quente" remover da plataforma que está no ar web/profiles/contrib/fflchprofile/modules/fflch_configs/src/installed.txt para ele não ser instalado novamente na rodada do cron
- com drush pm-uninstall desabilitar o módulos de todos sites que estão no ar
- subir nova plataforma e migrar os sites

**Comment by acesarfs** [comment]
> @acesarfs pode remover esse módulo. Lembrando que não basta remover do composer.json, é necessário:
> 
> * Remover do /web/profiles/contrib/fflchprofile/modules/fflch_configs/src/installed.txt
> * Remover do composer.json
> * "A quente" remover da plataforma que está no ar web/profiles/contrib/fflchprofile/modules/fflch_configs/src/installed.txt para ele não ser instalado novamente na rodada do cron
> * com drush pm-uninstall desabilitar o módulos de todos sites que estão no ar
> * subir nova plataforma e migrar os sites

Fiquei com dúvida se:
1. preciso fazer nessa ordem;
2. se o item "A quente" precisa ser feito já que o primeiro item já faz isso;
3. subir nova plataforma e migrar sites pode ser feito depois que eu fiz outras issues que modificam a plataforma do Drupal.

**Comment by thiagogomesverissimo** [comment]
Sim, nesta ordem. Tem que fazer a quente, pois se você migrar os sites e eles tiverem com um módulo que não existe na nova plataforma,  o site vai morrer na migração.

**Comment by acesarfs** [comment]
Antes de fechar essa issue, fiquei com uma dúvida: o módulo foi removido do composer.json, mas precisava fazer alguma coisa com o composer.lock? Eu não fiz nada nele.

**Comment by thiagogomesverissimo** [comment]
sim, composer update;

**Comment by acesarfs** [comment]
Entendo que com a plataforma já criada, não adianta fazer agora. Só na próxima. Acho que por conta de não ter feito isso, o módulo ainda vai aparecer nos sites migrados para essa plataforma. Isso é algo que inviabiliza a  migração?
