### ISSUE TITLE
Liberar a permissão de webform templates 

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#146]

**Comment by thiagogomesverissimo** [comment]
@acesarfs tem uma permissão que libera essa função. Pode, identificá-la e inserilá em user.role.fflch.yml ?

**Comment by acesarfs** [comment]
Endereço: [site.fflch.usp.br]/admin/people/permissions

Access the webform overview page
Get an overview of all webforms.

Permissão:   - 'access webform overview'

**Comment by acesarfs** [comment]
Fix um pull-request, mas acho que deveria ter comitado direto no upstream do drupal. Faço assim nas próximas issues do drupal?

**Comment by thiagogomesverissimo** [comment]
Neste projeto, drupal, pode commitar direto no upstream.

**Comment by thiagogomesverissimo** [comment]
Só por curiosidade, é essa permissão mesmo?
Verificou se o módulo templates estava habilitado?

**Comment by thiagogomesverissimo** [comment]
Pois se não estiver, tem.que habilita-lo globalmente

**Comment by acesarfs** [comment]
O módulo Webform Templates (webform_templates) não está habilitado por padrão. Quando é habilitado a guia Templates aparece pro usuário já que a permissão já está setada independente do modulo desabilitado. De qualquer forma, vou colocar o módulo no arquivo installed.txt.

**Comment by acesarfs** [comment]
Complementei colocando o módulo no arquivo installed.txt.
