### ISSUE TITLE
Inventário de módulos 

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#147]
Fazer levantamento dos módulos do composer.json:

- para que serve
- tem versão para o 9
- é realmente usado em algum site

**Comment by acesarfs** [comment]
Fiz o levantamento, mas não consegui disponibilizar no Drive Compartilhado pelo motivo que mencionei. As Informações de "para que serve" e "tem versão para o 9" peguei na página web de cada módulo. A Informação "é realmente usado em algum site" peguei a partir do resultado do comando do drush que informa os módulos habilitados para o site.
É para confirmar se está somente habilitado e não está sendo usado realmente?

**Comment by thiagogomesverissimo** [comment]
Sim,.a ideia é que conhecemos os módulos e para que eles servem. Mas podemos preencher essa informações mais para frente, pois vamos deixar aqui público quais módulos tem na nossa instalação e por que.

**Comment by acesarfs** [comment]
Realmente não acessei cada site para ver quais módulos são realmente usados, pois, precisaria de muito mais tempo para levantar essas informações.
Só pra reforçar, ainda não consigo salvar o levantamento no drive compartilhado, portanto, está acessível apenas para mim.

**Comment by acesarfs** [comment]
Vou fechar essa issue e, quando formos voltar ao assunto, eu a reabro.

**Comment by thiagogomesverissimo** [comment]
Pode compartilhar a planilha que fez comigo?

**Comment by thiagogomesverissimo** [comment]
Vou deixar aberto e pinada, pois esotu mexendo no composer.json

**Comment by thiagogomesverissimo** [comment]
O aegir agora suporta drupal 9, agora podemos iniciar os procedimentos de mudança.

Para isso deve-se checar se esse levantamento continua atualizado:

https://docs.google.com/spreadsheets/d/1ygAgSbHwDV3VSu4Jfl4rX2uue7IXt785YeKGEglbn0c/edit?usp=sharing

**Comment by thiagogomesverissimo** [comment]
Vou fechar, pois teremos que recomeçar esse levantamento.
