### ISSUE TITLE
aegan-subtheme: dropdown não funciona quando há Descrição

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#150]
O menu azul (o principal) está com problema quando é colocado o campo "Descrição" nos itens, o dropdown não funciona

**Comment by ricardfo** [comment]
Em que site apresentou o problema? Por que em meu teste local isso não ocorreu.

**Comment by thiagogomesverissimo** [comment]
Nos subitens de internacional em https://www.fflch.usp.br/ coloque uma descrição para cada item. Depois veja que o dropown quebra

**Comment by ricardfo** [comment]
Coloque descrições nos subitens do site que entendi sendo o da CCINT e não ocorreu problema.
Acho que estou fazendo algo errado, mas deixei as descrições lá.

**Comment by thiagogomesverissimo** [comment]
Estranho, também fiz aqui e o erro sumiu. Fechando a issue.
