### ISSUE TITLE
Verificar por que o site do centrodametropole é o único que não roda o cron

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#151]

**Comment by thiagogomesverissimo** [comment]
@acesarfs e @ricardfo vocês podem ver isso?

`drush @centrodametropole.fflch.usp.br cr`

**Comment by ricardfo** [comment]
Fiz o teste na plataforma drupal8.9.3b e o cache rebuild funcionou.

**Comment by thiagogomesverissimo** [comment]
O cache rebuid sim. Mas o cron não:
`drush @centrodametropole.fflch.usp.br cro`

Estou reabrindo a issue

**Comment by ricardfo** [comment]
Eu acho que é porque ele tenta desinstalar o módulo **Comment**  mas ele está sendo usado no site.
Eu deixei o erro no home do root no servidor.

**Comment by ricardfo** [comment]
Rodei o comando: `drush php-eval 'field_purge_batch(1000);'` e depois `drush pm-uninstall comment` e o módulo foi desinstalado com sucesso.
Agora o cron executa com sucesso mas têm um warning que é sobre search_api que está tentando salvar números negativos  no campo score da tabela **search_api_db_search_index_text (item_id, field_name, word, score)**.
