### ISSUE TITLE
Pesquisa módulo que permita geolocalização (lat - lon) em um tipo de conteúdo, assim podemos mostrar um mapa marcando onde tem node - CCInt

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#152]
Implementar campos para geolocalização de nodes, que será usado no tipo de conteúdo convênios. Depois disso, mostrar convênios em um mapa mundi.

**Comment by ricardfo** [comment]
Implementado no commit #4342ac7.
