### ISSUE TITLE
Liberar uma permissão do módulo entity print

### ISSUE THREAD

**Issue by sa0tome** [fflch/drupal#155]
![photo_2020-09-08_14-13-09](https://user-images.githubusercontent.com/57924632/92507493-73239680-f1dd-11ea-9c0a-6e5a8e5c984a.jpg)

**Comment by thiagogomesverissimo** [comment]
Augusto, essa é um permissão do entity print. Pode liberar?

**Comment by acesarfs** [comment]
Entity Print
  Content: Use all print engines

  - 'entity print access type node'
