### ISSUE TITLE
Instalação do Módulo Previous/Next pagination na página do LISA

### ISSUE THREAD

**Issue by st-ricardof** [fflch/drupal#157]
Por favor, implementar o seguinte módulo https://www.drupal.org/project/nextpre no tipo de conteúdo "Cadastro de foto" do site http://lisa.fflch.usp.br.

A intenção é que dentro da página do tipo de conteúdo, como por exemplo, http://lisa.fflch.usp.br/node/3001 que é o conteúdo AP-APINAYÉ-0001, tenha uma botão de anterior|próximo. Em que o clique no próximo permitiria seguir para o conteúdo AP-APINAYÉ-0002 (http://lisa.fflch.usp.br/node/3002).

O ideal é que este controle de navegação seguisse a ordem de listagem da página http://lisa.fflch.usp.br/imagens_bd.
Nesta página é possível fazer buscas e os botões prev|next deveria seguir a ordem destas buscas. 

Por exemplo, a ordenação padrão é : AP-APINAYÉ-0001, AP-APINAYÉ-0002, AR-ARAWETÉ-0001...
Se eu entrar em AP-APINAYÉ-0002 e clicar em próximo, deve seguir para AR-ARAWETÉ-0001.
No entanto se eu pesquisar por "AP-APINAYÉ", terei o seguinte resultado: AP-APINAYÉ-0001 e AP-APINAYÉ-0002.
Agora se eu entrar entrar em AP-APINAYÉ-0002 e clicar em próximo, **não** deve seguir para AR-ARAWETÉ-0001, pois ele não faz parte do resultado da minha busca. O comportamento esperado é voltar para AP-APINAYÉ-0001  ou ter o botão próximo como desabilitado, uma vez que chegou no último item da lista.

**Comment by ricardfo** [comment]
O módulo navega pelo tipo de conteúdo e não pelo resultado da busca. Se resultado da busca trouxer 20 resultados mas o tipo de conteúdo tiver 50 registros, assim que clicar em um resultado e carregar node, o módulo possibilitará a pessoa navegar em todos os nodes e a ordem é pelo nid do contéudo.
Isso servirá para o Ricardo Dionisio?

**Comment by ricardfo** [comment]
Abrindo novamente porque fechei erroneamente.
Esperando resposta do questionamento anterior.
