### ISSUE TITLE
"No access to execute Download PDF on the Content"

### ISSUE THREAD

**Issue by sa0tome** [fflch/drupal#158]
![image](https://user-images.githubusercontent.com/57924632/93491498-1fe9cc00-f8e0-11ea-9ec4-6b54d560ab77.png)

Ainda não consigo fazer download em PDF de páginas estáticas.

**Comment by acesarfs** [comment]
Pelo que verifiquei, a permissão será setada quando o(s) site(s) em questão forem migrados de plataforma.
