### ISSUE TITLE
Liberar a pemissão "Registro de log recentes" para role FFLCH

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#170]

**Comment by acesarfs** [comment]
Achei uma permissão que libera o menu Relatórios com exceção de duas opções: Atualizações de tradução disponíveis e Relatório de status. As demais opções são a opção dessa issue e outras seis opções que acho que não é um problema estarem liberadas. O que você acha?

**Comment by acesarfs** [comment]
Liberada a opção por meio do menu Relatórios:

Ver relatórios do site
  - 'access site reports'
