### ISSUE TITLE
install views_field_view

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#183]
https://www.drupal.org/project/views_field_view

**Comment by acesarfs** [comment]
Esse módulo precisa estar habilitado por padrão ou apenas na relação de módulos disponíveis?

**Comment by thiagogomesverissimo** [comment]
apenas na relação de módulos disponíveis

**Comment by acesarfs** [comment]
Comitei diretamente, sem fazer pull request. Então, estou fechando a issue manualmente.
