### ISSUE TITLE
Permissão de Usuário Anônimo não deve usar usar o IMCE para fazer upload de arquivos

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#187]
Atualmente está permitindo quando uma campo do webform tem editor do ckeditor

**Comment by acesarfs** [comment]
Não consegui reproduzir o problema. Não sei se alguém já resolveu. A permissão padrão do ckeditor esta para apenas os papéis Administrador e FFLCH e campos do Webform do tipo Formato de texto não aparecem os botões para usuário anônimo.
Exemplo:
![image](https://user-images.githubusercontent.com/6999014/113725502-c1dcd480-96c9-11eb-8326-e4012fec376c.png)

**Comment by thiagogomesverissimo** [comment]
sim, eu acabei corrigindo dado a urgência. Mas era esse campo mesmo, estava aparecendo o ckeditor para anônimos
