### ISSUE TITLE
Instalação de módulo bootstrap_horizontal_tabs

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#193]
https://sites.fflch.usp.br/chamados/259/168
site: filosofia.fflch.usp.br
status: aberto
tipo: Solicitação de módulo

Instalar e habilitar https://www.drupal.org/project/bootstrap_horizontal_tabs

O módulo cria um Tipo de Conteúdo em abas. Já testei, funciona.

**Comment by ricardfo** [comment]
No meu teste têm um problema que na primeira aba foi adicionado um classe de nome **show** que possui o display como **block** e isso gera um espaço superior nas outras abas com o tamanho da primeira aba.
Pelo que vi, a classe foi colocada para corrigir o problema com o bootstrap 4, porque ele substituiu a classe **in** no bootstrap 3 para **show** no bootstrap 4.
Isso dá para corrigir tirando a classe no template do módulo, devemos instalar?

**Comment by thiagogomesverissimo** [comment]
Vamos mudar para Bootstrap 4. Verificar se o mesmo ocorre lá.

**Comment by ricardfo** [comment]
https://sites.fflch.usp.br/chamados/259/168

Veja o meu comentário no chamado, devo instalar o módulo? Para mim não ficou claro se é necessário o módulo.

**Comment by thiagogomesverissimo** [comment]
Pode, mas não habilite em todos sites, somente no da filosofia.
