### ISSUE TITLE
Rodar um comando drush para garantir que todos sites tenham o módulo fflch_configs habilitado

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#195]

**Comment by acesarfs** [comment]
O comando é pra ser rodado com qual periodicidade? Coloca no cron?

O comando abaixo, foi testado na minha máquina Aegir local, e executado dentro do diretório sites.
for i in $(ls . | grep fflch.usp.br); do echo $i; drush @$i en fflch_configs -y; done

**Comment by thiagogomesverissimo** [comment]
uma vez por dia

Veja como exemplo: https://github.com/fflch/provisioner/blob/master/templates/aegir/modules_usage.sh.j2
Pode criar um parecido, para caso alguém desabilite, ele volte a ser habilitado por esse script.
