### ISSUE TITLE
módulo colorbutton com problema - olhar console.log()

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#200]
$/< http://127.0.0.1:8088/libraries/ckeditor/plugins/colorbutton/plugin.js?t=qnx4lw:586
    1 http://127.0.0.1:8088/core/assets/vendor/ckeditor/ckeditor.js?v=4.14.1:10
    c http://127.0.0.1:8088/core/assets/vendor/ckeditor/ckeditor.js?v=4.14.1:10
    fire http://127.0.0.1:8088/core/assets/vendor/ckeditor/ckeditor.js?v=4.14.1:11
    fire http://127.0.0.1:8088/core/assets/vendor/ckeditor/ckeditor.js?v=4.14.1:13
    fireOnce http://127.0.0.1:8088/core/assets/vendor/ckeditor/ckeditor.js?v=4.14.1:12
    fireOnce http://127.0.0.1:8088/core/assets/vendor/ckeditor/ckeditor.js?v=4.14.1:13
    b http://127.0.0.1:8088/core/assets/vendor/ckeditor/ckeditor.js?v=4.14.1:346
    setMode http://127.0.0.1:8088/core/assets/vendor/ckeditor/ckeditor.js?v=4.14.1:352
plugin.js:615:32

**Comment by ricardfo** [comment]
Existe uma função que o módulo usa que foi adicionada no ckeditor da versão 4.15.1 e o core do Drupal usa a 4.14.1.
Mesmo eu atualizando a versão do ckeditor que têm no composer.json para 4.15.1 o erro continua, mas quando fiz o downgrade para a versão do core o erro parou.
O Drupal atualizou o ckeditor para 4.15 na release 9.1.2.
Devemos fazer o downgrade no composer.json para 4.14.1?

**Comment by ricardfo** [comment]
Problema resolvido com o downgrade da versão do ckeditor no commit cd9e304.
