### ISSUE TITLE
Instalação de módulo header_and_footer_scripts

### ISSUE THREAD

**Issue by acesarfs** [fflch/drupal#206]
https://sites.fflch.usp.br/chamados/259/169
site: filosofia.fflch.usp.br
status: aberto
tipo: Solicitação de módulo
https://www.drupal.org/project/header_and_footer_scripts

módulo para adicionar bibliotecas externas de css e js sem tem inserir pelo Asset Injector

**Comment by acesarfs** [comment]
Fiz os procedimentos na minha máquina, mas não subi pro Github. Precisou atualizar a versão do dompdf.
Não sei se vai esperar a versão do Drupal 9.

**Comment by thiagogomesverissimo** [comment]
Pode subir na D8 e faz mer na D9

**Comment by thiagogomesverissimo** [comment]
Módulo adicionado
