### ISSUE TITLE
Busca e ordenação por campo referenciado em uma view

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#235]
Implementar busca por autor e ordenação por autor em:

http://ppglc.fflch.usp.br/livros

**Comment by acesarfs** [comment]
Pra resolver, primeiro eu adicionei um relacionamento para o conteúdo Docentes, que são os autores, e depois, em Critérios de Filtragem, adicionei o campo Título e associei a esse relacionamento.
