### ISSUE TITLE
Dar permissão para fflch usar metatag

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#54]

**Comment by acesarfs** [comment]
O que é metatag?

**Comment by ricardfo** [comment]
Por favor explique melhor o que seria **metatag**, não achei nada nas permissões com esse termo.

**Comment by thiagogomesverissimo** [comment]
Tem um módulo que já está no composer: https://www.drupal.org/project/metatag

O que precisa ser fieto:
1. instalá-lo globalmente, em installaed.txt
2. Verificar as permissões que ele disponibiliza e liberar para role FFLCH
