### ISSUE TITLE
No módulo de auditoria fflch_audit, mostrar quantos formulários não tem captcha

### ISSUE THREAD

**Issue by acesarfs** [fflch/drupal#61]

**Comment by thiagogomesverissimo** [comment]
audit

submissões: select * from webform_submission;

Emails da caixa de sáida: select * from mail_safety_dashboard;

últimos logins: login_tracker: select * from login_tracker;

falta ver se os webforms tem captchas??

**Comment by thiagogomesverissimo** [comment]
capctha é obrigatório em todos forms agora
