### ISSUE TITLE
Módulo para ocultar os campos

### ISSUE THREAD

**Issue by marisabarros11** [fflch/drupal#80]
Automatic Entity Label
[https://www.drupal.org/project/auto_entitylabel]  
Referente ao chamado do site estudoscomparados.fflch.usp.br

**Comment by thiagogomesverissimo** [comment]
@ricardfo além de instalar deve verificar se alguma permissão tem que ser habilitada.

**Comment by ricardfo** [comment]
Têm essas permissões, autoriza todas?

- Formulário de contato: Administer automatic entity labels
- Tipo de conteúdo: Administer automatic entity labels
- Custom block type: Administer automatic entity labels
- Paragraphs type: Administer automatic entity labels
- Shortcut set: Administer automatic entity labels
- Vocabulário de taxonomia: Administer automatic entity labels
- Webform: Administer automatic entity labels

**Comment by thiagogomesverissimo** [comment]
sim
