### ISSUE TITLE
Dar permissão para o usuário fflch em "Webform submission: Use all print engines"

### ISSUE THREAD

**Issue by marisabarros11** [fflch/drupal#88]
Demanda do site ppghe.fflch.usp.br

**Comment by thiagogomesverissimo** [comment]
@acesarfs pode identificar qual permissão é essa e colocar no role.fflch.yml ?

**Comment by acesarfs** [comment]
Webform submission: Use all print engines

Permissão:   - 'entity print access type webform_submission'

**Comment by acesarfs** [comment]
Coloquei a permissão no role.fflch.yml, mas não achei o lugar em qual página, no Webform ou em Configurações, ela fica.

**Comment by thiagogomesverissimo** [comment]
ok, se já aplicou, estou fechando a issue
