### ISSUE TITLE
Ver relação de dois tipos de conteúdo na view

### ISSUE THREAD

**Issue by acesarfs** [fflch/drupal#90]
Site Literatura Brasileira (Dissertações e Teses)

**Comment by thiagogomesverissimo** [comment]
@acesarfs resolvido? Podemos fechar essa issue?

**Comment by acesarfs** [comment]
Teoricamente ainda não foi resolvido, mas a solução, na época, foi retirar a opção de consulta por Autor na View. Mesmo após tanto tempo da solução adotada, se o administrador do site sentir falta dessa opção, isso cairá no suporte de sites. Sendo assim, acho que essa issue pode ser fechada. O que acha?

**Comment by thiagogomesverissimo** [comment]
Ok
