### ISSUE TITLE
Quando um site é criado, o drupal manda um email automático. Desativar esse envio (pessoas estão tentando criar conta local)

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#94]

**Comment by thiagogomesverissimo** [comment]
@ricardfo você pode procurar o arquivo yml que desativa os envios de email na criação do site e colocar no nosso profile?

**Comment by ricardfo** [comment]
Não encontrei nenhum arquivo yml que configura o envio de email na criação do site. Mas achei o arquivo que possui  a mensagem que é enviada:

- /var/aegir/.drush/provision/platform/provision_welcome_mail.inc

Então, quem envia o email é o drush, achei essas duas discuções sobre isso:

- https://www.drupal.org/node/2691971

- https://www.drupal.org/project/phpconfig/issues/1826652#comment-12566468

Não sei como aplicar a configuração na hora de executar o drush site-install no nosso profile
